[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.zhigu34.stream", custom_domain = true },
  { pattern = "quay.zhigu34.stream", custom_domain = true },
  { pattern = "gcr.zhigu34.stream", custom_domain = true },
  { pattern = "k8s-gcr.zhigu34.stream", custom_domain = true },
  { pattern = "k8s.zhigu34.stream", custom_domain = true },
  { pattern = "ghcr.zhigu34.stream", custom_domain = true },
  { pattern = "cloudsmith.zhigu34.stream", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.zhigu34.stream", custom_domain = true }
